/**
 * The manual provider catalog shown in the reviewer config. The user picks a
 * provider first (instead of relying only on key-prefix auto-detection); the
 * entry supplies the adapter, default endpoint and default model, and the
 * user only adds the API key (or none, for local servers).
 *
 * Every entry stores its FULL base URL prefix — the OpenAI adapter appends
 * `/chat/completions` (electron/reviewer/providers/openai.ts) and the live
 * model list appends `/models` (electron/model-list.ts) — so the prefix must
 * include the `/v1` (or provider-native) path.
 *
 * Adapters: 'openai' = OpenAI-compatible chat/completions, 'anthropic' =
 * Anthropic messages API, 'ollama' = Ollama /api/chat. Most providers are
 * OpenAI-compatible and reuse the existing 'openai' adapter.
 */

export type AdapterKind = 'openai' | 'anthropic' | 'ollama';

export interface ProviderCatalogEntry {
  /** Stable id persisted in settings (`reviewer.providerId`). */
  id: string;
  /** Human-friendly label for the picker. */
  name: string;
  /** Picker grouping. */
  group: 'cloud' | 'local' | 'custom';
  /** Which provider client adapter to build. */
  adapter: AdapterKind;
  /** Full base URL prefix ('' = user must supply one, custom only). */
  baseUrl: string;
  /** Suggested default model. */
  defaultModel: string;
  /** Offline model suggestions (the live list from the API is preferred). */
  models?: string[];
  /** Whether an API key is required. */
  auth: 'key' | 'none' | 'optional';
  /** Placeholder shown in the API key field. */
  keyHint?: string;
  /** Accuracy / usage note. */
  notes?: string;
}

/* ------------------------------------------------------------------ *
 * Cloud — first-party and OpenAI-compatible hosted APIs
 * ------------------------------------------------------------------ */

const cloud: ProviderCatalogEntry[] = [
  // first-party / native
  {
    id: 'openai',
    name: 'OpenAI',
    group: 'cloud',
    adapter: 'openai',
    baseUrl: 'https://api.openai.com/v1',
    defaultModel: 'gpt-4o',
    models: ['gpt-4o', 'gpt-5', 'gpt-5-mini', 'o4-mini'],
    auth: 'key',
    keyHint: 'sk-… (OpenAI key)',
  },
  {
    id: 'anthropic',
    name: 'Anthropic',
    group: 'cloud',
    adapter: 'anthropic',
    baseUrl: 'https://api.anthropic.com',
    defaultModel: 'claude-sonnet-4-5',
    models: ['claude-sonnet-4-5', 'claude-opus-4-1', 'claude-haiku-4-5', 'claude-3-7-sonnet-latest'],
    auth: 'key',
    keyHint: 'sk-ant-… (Anthropic key)',
  },
  {
    id: 'deepseek',
    name: 'DeepSeek',
    group: 'cloud',
    adapter: 'openai',
    baseUrl: 'https://api.deepseek.com/v1',
    defaultModel: 'deepseek-chat',
    models: ['deepseek-chat', 'deepseek-reasoner', 'deepseek-v4-pro', 'deepseek-v4-flash'],
    auth: 'key',
    keyHint: 'sk-… (DeepSeek key)',
    notes: 'OpenAI-compatible; reasoning model uses thinking fields.',
  },
  // major OpenAI-compatible
  {
    id: 'xai',
    name: 'xAI (Grok)',
    group: 'cloud',
    adapter: 'openai',
    baseUrl: 'https://api.x.ai/v1',
    defaultModel: 'grok-3-mini',
    models: ['grok-3-mini', 'grok-4'],
    auth: 'key',
    keyHint: 'xai-… (your xAI key)',
  },
  {
    id: 'groq',
    name: 'Groq',
    group: 'cloud',
    adapter: 'openai',
    baseUrl: 'https://api.groq.com/openai/v1',
    defaultModel: 'llama-3.3-70b-versatile',
    models: ['llama-3.3-70b-versatile', 'llama-3.1-8b-instant'],
    auth: 'key',
    keyHint: 'gsk_… (Groq key)',
  },
  {
    id: 'together',
    name: 'Together AI',
    group: 'cloud',
    adapter: 'openai',
    baseUrl: 'https://api.together.xyz/v1',
    defaultModel: 'meta-llama/Llama-3.3-70B-Instruct-Turbo',
    models: ['meta-llama/Llama-3.3-70B-Instruct-Turbo', 'meta-llama/Llama-3.1-8B-Instruct-Turbo', 'deepseek-ai/DeepSeek-V3'],
    auth: 'key',
    keyHint: '… (Together key)',
  },
  {
    id: 'openrouter',
    name: 'OpenRouter (aggregator)',
    group: 'cloud',
    adapter: 'openai',
    baseUrl: 'https://openrouter.ai/api/v1',
    defaultModel: 'openai/gpt-4o',
    models: ['openai/gpt-4o', 'anthropic/claude-sonnet-4.5', 'deepseek/deepseek-r1'],
    auth: 'key',
    keyHint: 'sk-or-… (OpenRouter key)',
    notes: 'Aggregator; routes to many models via one key.',
  },
  {
    id: 'perplexity',
    name: 'Perplexity',
    group: 'cloud',
    adapter: 'openai',
    baseUrl: 'https://api.perplexity.ai',
    defaultModel: 'sonar-pro',
    models: ['sonar-pro', 'sonar', 'sonar-reasoning-pro'],
    auth: 'key',
    keyHint: 'pplx-… (Perplexity key)',
  },
  {
    id: 'fireworks',
    name: 'Fireworks AI',
    group: 'cloud',
    adapter: 'openai',
    baseUrl: 'https://api.fireworks.ai/inference/v1',
    defaultModel: 'accounts/fireworks/models/llama-v3p3-70b-instruct',
    models: ['accounts/fireworks/models/llama-v3p3-70b-instruct', 'accounts/fireworks/models/deepseek-v3'],
    auth: 'key',
    keyHint: '… (Fireworks key)',
  },
  {
    id: 'mistral',
    name: 'Mistral AI (La Plateforme)',
    group: 'cloud',
    adapter: 'openai',
    baseUrl: 'https://api.mistral.ai/v1',
    defaultModel: 'mistral-large-latest',
    models: ['mistral-large-latest', 'mistral-small-latest', 'ministral-8b'],
    auth: 'key',
    keyHint: '… (Mistral key)',
  },
  {
    id: 'cohere',
    name: 'Cohere',
    group: 'cloud',
    adapter: 'openai',
    baseUrl: 'https://api.cohere.ai/compatibility/v1',
    defaultModel: 'command-r-plus',
    models: ['command-r-plus', 'command-r', 'c4ai-aya-expanse-8b'],
    auth: 'key',
    keyHint: '… (Cohere key)',
    notes: 'OpenAI-compatible compatibility endpoint.',
  },
  {
    id: 'huggingface',
    name: 'Hugging Face Inference',
    group: 'cloud',
    adapter: 'openai',
    baseUrl: 'https://router.huggingface.co/v1',
    defaultModel: 'meta-llama/Llama-3.3-70B-Instruct',
    models: ['meta-llama/Llama-3.3-70B-Instruct', 'Qwen/Qwen2.5-72B-Instruct'],
    auth: 'key',
    keyHint: 'hf_… (Hugging Face token)',
  },
  {
    id: 'nvidia',
    name: 'NVIDIA NIM',
    group: 'cloud',
    adapter: 'openai',
    baseUrl: 'https://integrate.api.nvidia.com/v1',
    defaultModel: 'meta/llama-3.3-70b-instruct',
    models: ['meta/llama-3.3-70b-instruct', 'qwen/qwen2.5-72b-instruct'],
    auth: 'key',
    keyHint: 'nvapi-… (NVIDIA API key)',
  },
  {
    id: 'cerebras',
    name: 'Cerebras',
    group: 'cloud',
    adapter: 'openai',
    baseUrl: 'https://api.cerebras.ai/v1',
    defaultModel: 'llama-3.3-70b',
    models: ['llama-3.3-70b', 'llama-4-scout'],
    auth: 'key',
    keyHint: '… (Cerebras key)',
  },
  {
    id: 'upstage',
    name: 'Upstage (Solar)',
    group: 'cloud',
    adapter: 'openai',
    baseUrl: 'https://api.upstage.ai/v1',
    defaultModel: 'solar-pro',
    models: ['solar-pro', 'solar-mini'],
    auth: 'key',
    keyHint: 'up_… (Upstage key)',
  },
  {
    id: 'nebius',
    name: 'Nebius AI Studio',
    group: 'cloud',
    adapter: 'openai',
    baseUrl: 'https://api.nebius.ai/v1',
    defaultModel: 'meta-llama/Llama-3.3-70B-Instruct',
    models: ['meta-llama/Llama-3.3-70B-Instruct', 'deepseek-ai/DeepSeek-V3'],
    auth: 'key',
    keyHint: '… (Nebius key)',
  },
  {
    id: 'deepinfra',
    name: 'DeepInfra',
    group: 'cloud',
    adapter: 'openai',
    baseUrl: 'https://api.deepinfra.com/v1/openai',
    defaultModel: 'meta-llama/Llama-3.3-70B-Instruct',
    models: ['meta-llama/Llama-3.3-70B-Instruct', 'Qwen/Qwen2.5-72B-Instruct'],
    auth: 'key',
    keyHint: '… (DeepInfra key)',
  },
  {
    id: 'siliconflow',
    name: 'SiliconFlow',
    group: 'cloud',
    adapter: 'openai',
    baseUrl: 'https://api.siliconflow.cn/v1',
    defaultModel: 'deepseek-ai/DeepSeek-V3',
    models: ['deepseek-ai/DeepSeek-V3', 'Qwen/Qwen2.5-72B-Instruct'],
    auth: 'key',
    keyHint: 'sk-… (SiliconFlow key)',
  },
  {
    id: 'novita',
    name: 'Novita AI',
    group: 'cloud',
    adapter: 'openai',
    baseUrl: 'https://api.novita.ai/v3/openai',
    defaultModel: 'meta-llama/llama-3.3-70b-instruct',
    models: ['meta-llama/llama-3.3-70b-instruct', 'deepseek/deepseek-v3'],
    auth: 'key',
    keyHint: '… (Novita key)',
  },
  {
    id: 'hyperbolic',
    name: 'Hyperbolic',
    group: 'cloud',
    adapter: 'openai',
    baseUrl: 'https://api.hyperbolic.xyz/v1',
    defaultModel: 'meta-llama/Llama-3.3-70B-Instruct',
    models: ['meta-llama/Llama-3.3-70B-Instruct', 'deepseek-ai/DeepSeek-V3'],
    auth: 'key',
    keyHint: '… (Hyperbolic key)',
  },
  {
    id: 'sambanova',
    name: 'SambaNova',
    group: 'cloud',
    adapter: 'openai',
    baseUrl: 'https://api.sambanova.ai/v1',
    defaultModel: 'Meta-Llama-3.3-70B-Instruct',
    models: ['Meta-Llama-3.3-70B-Instruct', 'Meta-Llama-3.1-8B-Instruct'],
    auth: 'key',
    keyHint: '… (SambaNova key)',
  },
  {
    id: 'gemini',
    name: 'Google Gemini (OpenAI-compatible)',
    group: 'cloud',
    adapter: 'openai',
    baseUrl: 'https://generativelanguage.googleapis.com/v1beta/openai',
    defaultModel: 'gemini-2.0-flash',
    models: ['gemini-2.0-flash', 'gemini-2.5-pro', 'gemini-1.5-pro'],
    auth: 'key',
    keyHint: 'AIza… (Google API key)',
    notes: 'Uses the OpenAI-compatibility surface of Gemini.',
  },
  {
    id: 'writer',
    name: 'Writer (Palmyra)',
    group: 'cloud',
    adapter: 'openai',
    baseUrl: 'https://api.writer.com/v1',
    defaultModel: 'palmyra-x',
    models: ['palmyra-x', 'palmyra-creative'],
    auth: 'key',
    keyHint: '… (Writer key)',
  },
  {
    id: 'ai21',
    name: 'AI21',
    group: 'cloud',
    adapter: 'openai',
    baseUrl: 'https://api.ai21.com/v1',
    defaultModel: 'jamba-1.5-large',
    models: ['jamba-1.5-large', 'jamba-1.5-mini'],
    auth: 'key',
    keyHint: '… (AI21 key)',
  },
  {
    id: 'portkey',
    name: 'Portkey (gateway)',
    group: 'cloud',
    adapter: 'openai',
    baseUrl: 'https://api.portkey.ai/v1',
    defaultModel: 'openai/gpt-4o',
    models: ['openai/gpt-4o'],
    auth: 'key',
    keyHint: 'sk-… (Portkey key)',
    notes: 'Single gateway to many providers.',
  },
  {
    id: 'lepton',
    name: 'Lepton AI',
    group: 'cloud',
    adapter: 'openai',
    baseUrl: 'https://api.lepton.ai/v1',
    defaultModel: 'llama3.1',
    models: ['llama3.1', 'qwen'],
    auth: 'key',
    keyHint: '… (Lepton key)',
  },
  {
    id: 'friendli',
    name: 'FriendliAI',
    group: 'cloud',
    adapter: 'openai',
    baseUrl: 'https://api.friendli.ai/v1',
    defaultModel: 'deepseek-ai/deepseek-v3',
    models: ['deepseek-ai/deepseek-v3', 'meta-llama-3.3-70b'],
    auth: 'key',
    keyHint: '… (Friendli key)',
  },
  {
    id: 'predibase',
    name: 'Predibase',
    group: 'cloud',
    adapter: 'openai',
    baseUrl: 'https://api.predibase.com/v1',
    defaultModel: 'llama-3.1-8b-instruct',
    models: ['llama-3.1-8b-instruct'],
    auth: 'key',
    keyHint: '… (Predibase key)',
  },
  {
    id: 'anyscale',
    name: 'AnyScale',
    group: 'cloud',
    adapter: 'openai',
    baseUrl: 'https://api.endpoints.anyscale.com/v1',
    defaultModel: 'meta-llama/Llama-3.3-70B-Instruct',
    models: ['meta-llama/Llama-3.3-70B-Instruct', 'deepseek-ai/DeepSeek-V3'],
    auth: 'key',
    keyHint: 'es-… (AnyScale key)',
  },
  {
    id: 'lambdalabs',
    name: 'Lambda (Chat API)',
    group: 'cloud',
    adapter: 'openai',
    baseUrl: 'https://api.lambdalabs.com/v1',
    defaultModel: 'llama-3.3-70b',
    models: ['llama-3.3-70b'],
    auth: 'key',
    keyHint: '… (Lambda key)',
  },
  {
    id: 'scaleway',
    name: 'Scaleway',
    group: 'cloud',
    adapter: 'openai',
    baseUrl: 'https://api.scaleway.ai/v1',
    defaultModel: 'meta-llama/Llama-3.3-70B-Instruct',
    models: ['meta-llama/Llama-3.3-70B-Instruct'],
    auth: 'key',
    keyHint: '… (Scaleway key)',
  },
  {
    id: 'vultr',
    name: 'Vultr (Inference)',
    group: 'cloud',
    adapter: 'openai',
    baseUrl: 'https://api.vultr.com/v1',
    defaultModel: 'meta-llama/llama-3.3-70b',
    models: ['meta-llama/llama-3.3-70b'],
    auth: 'key',
    keyHint: '… (Vultr key)',
  },
  {
    id: 'telnyx',
    name: 'Telnyx',
    group: 'cloud',
    adapter: 'openai',
    baseUrl: 'https://api.telnyx.com/v1',
    defaultModel: 'meta-llama/Llama-3.3-70B-Instruct',
    models: ['meta-llama/Llama-3.3-70B-Instruct'],
    auth: 'key',
    keyHint: 'KEY-… (Telnyx key)',
  },
  {
    id: 'clarifai',
    name: 'Clarifai',
    group: 'cloud',
    adapter: 'openai',
    baseUrl: 'https://api.clarifai.com/v1',
    defaultModel: 'meta-llama/Llama-3.3-70B-Instruct',
    models: ['meta-llama/Llama-3.3-70B-Instruct'],
    auth: 'key',
    keyHint: '… (Clarifai key)',
  },
  {
    id: 'edenai',
    name: 'Eden AI',
    group: 'cloud',
    adapter: 'openai',
    baseUrl: 'https://api.edenai.run/v1',
    defaultModel: 'meta-llama/Llama-3.3-70B-Instruct',
    models: ['meta-llama/Llama-3.3-70B-Instruct'],
    auth: 'key',
    keyHint: '… (Eden AI key)',
  },
  {
    id: 'shisa',
    name: 'Shisa AI',
    group: 'cloud',
    adapter: 'openai',
    baseUrl: 'https://api.shisa.ai/v1',
    defaultModel: 'shisa-llama-3-70b',
    models: ['shisa-llama-3-70b'],
    auth: 'key',
    keyHint: '… (Shisa key)',
  },
  {
    id: 'taobit',
    name: 'Bittensor (Taobot)',
    group: 'cloud',
    adapter: 'openai',
    baseUrl: 'https://api.taobit.ai/v1',
    defaultModel: 'meta-llama/llama-3-70b',
    models: ['meta-llama/llama-3-70b'],
    auth: 'key',
    keyHint: '… (Bittensor key)',
  },
  {
    id: 'inferless',
    name: 'Inferless',
    group: 'cloud',
    adapter: 'openai',
    baseUrl: 'https://api.inferless.com/v1',
    defaultModel: 'meta-llama/llama-3.3-70b',
    models: ['meta-llama/llama-3.3-70b'],
    auth: 'key',
    keyHint: '… (Inferless key)',
  },
  {
    id: 'liquidai',
    name: 'Liquid AI',
    group: 'cloud',
    adapter: 'openai',
    baseUrl: 'https://api.liquidai.com/v1',
    defaultModel: 'liquidai/LFM-70B',
    models: ['liquidai/LFM-70B', 'liquidai/LFM-40B'],
    auth: 'key',
    keyHint: '… (Liquid key)',
  },
  {
    id: 'parasail',
    name: 'Parasail',
    group: 'cloud',
    adapter: 'openai',
    baseUrl: 'https://api.parasail.ai/v1',
    defaultModel: 'meta-llama/llama-3.3-70b',
    models: ['meta-llama/llama-3.3-70b'],
    auth: 'key',
    keyHint: '… (Parasail key)',
  },
  {
    id: 'infermatic',
    name: 'Infermatic',
    group: 'cloud',
    adapter: 'openai',
    baseUrl: 'https://api.infermatic.ai/v1',
    defaultModel: 'meta-llama/llama-3.3-70b',
    models: ['meta-llama/llama-3.3-70b'],
    auth: 'key',
    keyHint: '… (Infermatic key)',
  },
  {
    id: 'kluster',
    name: 'Kluster.ai',
    group: 'cloud',
    adapter: 'openai',
    baseUrl: 'https://api.kluster.ai/v1',
    defaultModel: 'meta-llama/llama-3.3-70b',
    models: ['meta-llama/llama-3.3-70b'],
    auth: 'key',
    keyHint: '… (Kluster key)',
  },
  {
    id: 'polarapi',
    name: 'PolarAPI',
    group: 'cloud',
    adapter: 'openai',
    baseUrl: 'https://api.polarapi.com/v1',
    defaultModel: 'moonshot/kimi-k2',
    models: ['moonshot/kimi-k2', 'x-ai/grok-2'],
    auth: 'key',
    keyHint: '… (Polar key)',
  },
  {
    id: 'inferencenet',
    name: 'Inference.net',
    group: 'cloud',
    adapter: 'openai',
    baseUrl: 'https://api.inference.net/v1',
    defaultModel: 'meta-llama/llama-3.3-70b',
    models: ['meta-llama/llama-3.3-70b'],
    auth: 'key',
    keyHint: '… (Inference.net key)',
  },
  {
    id: 'featherless',
    name: 'Featherless',
    group: 'cloud',
    adapter: 'openai',
    baseUrl: 'https://api.featherless.ai/v1',
    defaultModel: 'meta-llama/llama-3.3-70b',
    models: ['meta-llama/llama-3.3-70b'],
    auth: 'key',
    keyHint: '… (Featherless key)',
  },
  {
    id: 'modal',
    name: 'Modal',
    group: 'cloud',
    adapter: 'openai',
    baseUrl: 'https://api.modal.com/v1',
    defaultModel: 'meta-llama/llama-3.1-8b',
    models: ['meta-llama/llama-3.1-8b'],
    auth: 'key',
    keyHint: '… (Modal key)',
  },
  {
    id: 'monsterapi',
    name: 'MonsterAPI',
    group: 'cloud',
    adapter: 'openai',
    baseUrl: 'https://api.monsterapi.ai/v1',
    defaultModel: 'meta-llama/llama-3-70b',
    models: ['meta-llama/llama-3-70b'],
    auth: 'key',
    keyHint: '… (MonsterAPI key)',
  },
  {
    id: 'nlpcloud',
    name: 'NLP Cloud',
    group: 'cloud',
    adapter: 'openai',
    baseUrl: 'https://api.nlpcloud.com/v1',
    defaultModel: 'llama-3.1-8b',
    models: ['llama-3.1-8b'],
    auth: 'key',
    keyHint: '… (NLP Cloud key)',
  },
  {
    id: 'gmi',
    name: 'GMI Cloud',
    group: 'cloud',
    adapter: 'openai',
    baseUrl: 'https://api.gmi-serve.com/v1',
    defaultModel: 'meta-llama/llama-3.3-70b',
    models: ['meta-llama/llama-3.3-70b'],
    auth: 'key',
    keyHint: '… (GMI key)',
  },
  {
    id: 'konko',
    name: 'Konko',
    group: 'cloud',
    adapter: 'openai',
    baseUrl: 'https://api.konko.ai/v1',
    defaultModel: 'meta-llama/Llama-3.3-70B-Instruct',
    models: ['meta-llama/Llama-3.3-70B-Instruct', 'mistralai/Mistral-7B-Instruct'],
    auth: 'key',
    keyHint: '… (Konko key)',
  },
  {
    id: 'unify',
    name: 'Unify',
    group: 'cloud',
    adapter: 'openai',
    baseUrl: 'https://api.unify.ai/v1',
    defaultModel: 'llama-3.3-70b',
    models: ['llama-3.3-70b'],
    auth: 'key',
    keyHint: '… (Unify key)',
  },
  // regional / long-tail
  {
    id: 'zhipu',
    name: 'Zhipu AI (GLM)',
    group: 'cloud',
    adapter: 'openai',
    baseUrl: 'https://open.bigmodel.cn/api/paas/v4',
    defaultModel: 'glm-4-plus',
    models: ['glm-4-plus', 'glm-4-air'],
    auth: 'key',
    keyHint: '… (Zhipu key)',
  },
  {
    id: 'moonshot',
    name: 'Moonshot AI (Kimi)',
    group: 'cloud',
    adapter: 'openai',
    baseUrl: 'https://api.moonshot.cn/v1',
    defaultModel: 'moonshot-v1-8k',
    models: ['moonshot-v1-8k', 'moonshot-v1-32k', 'moonshot-v1-128k'],
    auth: 'key',
    keyHint: 'sk-… (Moonshot key)',
    notes: 'Kimi models emit reasoning in a thinking field.',
  },
  {
    id: 'qwen',
    name: 'Alibaba (Qwen / DashScope)',
    group: 'cloud',
    adapter: 'openai',
    baseUrl: 'https://dashscope.aliyuncs.com/compatible-mode/v1',
    defaultModel: 'qwen-max',
    models: ['qwen-max', 'qwen-plus', 'qwen-turbo'],
    auth: 'key',
    keyHint: 'sk-… (DashScope key)',
    notes: 'OpenAI-compatible mode of DashScope.',
  },
  {
    id: 'minimax',
    name: 'MiniMax',
    group: 'cloud',
    adapter: 'openai',
    baseUrl: 'https://api.minimax.chat/v1',
    defaultModel: 'abab6.5s-chat',
    models: ['abab6.5s-chat', 'MiniMax-Text-01'],
    auth: 'key',
    keyHint: '… (MiniMax key)',
  },
  {
    id: 'yi',
    name: '01.AI (Yi)',
    group: 'cloud',
    adapter: 'openai',
    baseUrl: 'https://api.lingyiwanwu.com/v1',
    defaultModel: 'yi-large',
    models: ['yi-large', 'yi-medium'],
    auth: 'key',
    keyHint: '… (01.AI key)',
  },
  {
    id: 'baichuan',
    name: 'Baichuan',
    group: 'cloud',
    adapter: 'openai',
    baseUrl: 'https://api.baichuan-ai.com/v1',
    defaultModel: 'baichuan4',
    models: ['baichuan4', 'Baichuan3-Turbo'],
    auth: 'key',
    keyHint: 'sk-… (Baichuan key)',
  },
  {
    id: 'stepfun',
    name: 'StepFun',
    group: 'cloud',
    adapter: 'openai',
    baseUrl: 'https://api.stepfun.com/v1',
    defaultModel: 'step-1',
    models: ['step-1', 'step-1-8k'],
    auth: 'key',
    keyHint: '… (StepFun key)',
  },
  {
    id: 'doubao',
    name: 'Volcengine (Doubao / Ark)',
    group: 'cloud',
    adapter: 'openai',
    baseUrl: 'https://ark.cn-beijing.volces.com/api/v3',
    defaultModel: 'doubao-pro-32k',
    models: ['doubao-pro-32k', 'doubao-lite-32k'],
    auth: 'key',
    keyHint: '… (Ark key)',
    notes: 'Model id is the Ark endpoint id.',
  },
  {
    id: 'hunyuan',
    name: 'Tencent (Hunyuan)',
    group: 'cloud',
    adapter: 'openai',
    baseUrl: 'https://api.hunyuan.cloud.tencent.com/v1',
    defaultModel: 'hunyuan-pro',
    models: ['hunyuan-pro', 'hunyuan-standard'],
    auth: 'key',
    keyHint: '… (Tencent key)',
  },
  {
    id: 'yandex',
    name: 'Yandex GPT',
    group: 'cloud',
    adapter: 'openai',
    baseUrl: 'https://llm.api.cloud.yandex.ru/v1',
    defaultModel: 'yandexgpt-lite',
    models: ['yandexgpt-lite', 'yandexgpt'],
    auth: 'key',
    keyHint: '… (YC API key)',
    notes: 'Auth differs (folder + service key).',
  },
  {
    id: 'replicate',
    name: 'Replicate',
    group: 'cloud',
    adapter: 'openai',
    baseUrl: 'https://api.replicate.com/v1',
    defaultModel: 'meta/llama-3.1-405b-instruct',
    models: ['meta/llama-3.1-405b-instruct'],
    auth: 'key',
    keyHint: 'r8_… (Replicate token)',
  },
  {
    id: 'runpod',
    name: 'RunPod',
    group: 'cloud',
    adapter: 'openai',
    baseUrl: 'https://api.runpod.ai/v1',
    defaultModel: 'meta/llama-3.3-70b',
    models: ['meta/llama-3.3-70b'],
    auth: 'key',
    keyHint: '… (RunPod key)',
  },
  {
    id: 'openpipe',
    name: 'OpenPipe',
    group: 'cloud',
    adapter: 'openai',
    baseUrl: 'https://api.openpipe.ai/v1',
    defaultModel: 'meta-llama-3.1-8b',
    models: ['meta-llama-3.1-8b'],
    auth: 'key',
    keyHint: '… (OpenPipe key)',
  },
  {
    id: 'premai',
    name: 'PremAI',
    group: 'cloud',
    adapter: 'openai',
    baseUrl: 'https://api.premai.io/v1',
    defaultModel: 'meta-llama/Llama-3.1-70B',
    models: ['meta-llama/Llama-3.1-70B'],
    auth: 'key',
    keyHint: '… (PremAI key)',
  },
  {
    id: 'iflytek',
    name: 'iFlytek (Spark)',
    group: 'cloud',
    adapter: 'openai',
    baseUrl: 'https://spark-api-open.xf-yun.com/v1',
    defaultModel: 'generalv3.5',
    models: ['generalv3.5', '4.0Ultra'],
    auth: 'key',
    keyHint: '… (iFlytek key)',
  },
  {
    id: 'baidu',
    name: 'Baidu (Qianfan)',
    group: 'cloud',
    adapter: 'openai',
    baseUrl: 'https://qianfan.baidubce.com/v2',
    defaultModel: 'ernie-4.0-8k',
    models: ['ernie-4.0-8k', 'ernie-3.5-8k'],
    auth: 'key',
    keyHint: 'bce-v3/… (Baidu key)',
  },
  {
    id: 'internlm',
    name: 'InternLM',
    group: 'cloud',
    adapter: 'openai',
    baseUrl: 'https://api.internlm.com/v1',
    defaultModel: 'internlm2.5',
    models: ['internlm2.5', 'internlm3'],
    auth: 'key',
    keyHint: '… (InternLM key)',
  },
  {
    id: 'modelscope',
    name: 'ModelScope (Alibaba)',
    group: 'cloud',
    adapter: 'openai',
    baseUrl: 'https://api-inference.modelscope.cn/v1',
    defaultModel: 'Qwen/Qwen2.5-72B-Instruct',
    models: ['Qwen/Qwen2.5-72B-Instruct'],
    auth: 'key',
    keyHint: '… (ModelScope token)',
  },
  {
    id: 'nous',
    name: 'Nous Research',
    group: 'cloud',
    adapter: 'openai',
    baseUrl: 'https://api.nousresearch.com/v1',
    defaultModel: 'Hermes-3-Llama-3.1-405B',
    models: ['Hermes-3-Llama-3.1-405B'],
    auth: 'key',
    keyHint: '… (Nous key)',
  },
  {
    id: 'recursal',
    name: 'Recursal',
    group: 'cloud',
    adapter: 'openai',
    baseUrl: 'https://api.recursal.ai/v1',
    defaultModel: 'meta-llama-3.1-70b',
    models: ['meta-llama-3.1-70b'],
    auth: 'key',
    keyHint: '… (Recursal key)',
  },
  {
    id: 'chutes',
    name: 'Chutes',
    group: 'cloud',
    adapter: 'openai',
    baseUrl: 'https://chutes.ai/v1',
    defaultModel: 'deepseek-ai/DeepSeek-V3',
    models: ['deepseek-ai/DeepSeek-V3', 'meta-llama/llama-3.3-70b'],
    auth: 'key',
    keyHint: '… (Chutes key)',
  },
  {
    id: 'baseten',
    name: 'Baseten',
    group: 'cloud',
    adapter: 'openai',
    baseUrl: 'https://api.baseten.co/v1',
    defaultModel: 'meta-llama-3.1-70b',
    models: ['meta-llama-3.1-70b'],
    auth: 'key',
    keyHint: '… (Baseten key)',
  },
  {
    id: 'vercel-gateway',
    name: 'Vercel AI Gateway',
    group: 'cloud',
    adapter: 'openai',
    baseUrl: 'https://ai-gateway.vercel.sh/v1',
    defaultModel: 'openai/gpt-4o',
    models: ['openai/gpt-4o'],
    auth: 'key',
    keyHint: '… (Vercel key)',
    notes: 'Unified gateway to many providers.',
  },
  {
    id: 'cloudflare',
    name: 'Cloudflare Workers AI',
    group: 'cloud',
    adapter: 'openai',
    baseUrl: 'https://api.cloudflare.com/client/v4/accounts/REPLACE_ACCOUNT_ID/ai/v1',
    defaultModel: '@cf/meta/llama-3.3-70b-instruct-fp8-fast',
    models: ['@cf/meta/llama-3.3-70b-instruct-fp8-fast'],
    auth: 'key',
    keyHint: '… (Cloudflare API token)',
    notes: 'Replace the account id in the base URL.',
  },
  {
    id: 'jina',
    name: 'Jina (Reader/LLM)',
    group: 'cloud',
    adapter: 'openai',
    baseUrl: 'https://api.jina.ai/v1',
    defaultModel: 'jina-ai/Jina-Starlight-72b',
    models: ['jina-ai/Jina-Starlight-72b'],
    auth: 'key',
    keyHint: 'jina_… (Jina key)',
  },
  {
    id: 'sakana',
    name: 'Sakana AI',
    group: 'cloud',
    adapter: 'openai',
    baseUrl: 'https://api.sakana.ai/v1',
    defaultModel: 'sakana-ai/sakana-72b',
    models: ['sakana-ai/sakana-72b'],
    auth: 'key',
    keyHint: '… (Sakana key)',
  },
  {
    id: 'watsonx',
    name: 'IBM watsonx.ai',
    group: 'cloud',
    adapter: 'openai',
    baseUrl: 'https://us-south.ml.cloud.ibm.com/v1',
    defaultModel: 'meta-llama/llama-3-70b-instruct',
    models: ['meta-llama/llama-3-70b-instruct'],
    auth: 'key',
    keyHint: 'bx-… (IBM API key)',
    notes: 'Scoped to a region; adjust the base URL if needed.',
  },
  {
    id: 'databricks',
    name: 'Databricks (Foundation Model)',
    group: 'cloud',
    adapter: 'openai',
    baseUrl: 'https://REPLACE_WORKSPACE.cloud.databricks.com/serving-endpoints',
    defaultModel: 'meta-llama-3.3-70b-instruct',
    models: ['meta-llama-3.3-70b-instruct'],
    auth: 'key',
    keyHint: 'dapi… (Databricks token)',
    notes: 'Workspace-specific base URL.',
  },
  {
    id: 'vertex-ai',
    name: 'Google Vertex AI (OpenAI-compatible)',
    group: 'cloud',
    adapter: 'openai',
    baseUrl: 'https://REPLACE_REGION-aiplatform.googleapis.com/v1beta1/projects/REPLACE_PROJECT/locations/REPLACE_REGION/endpoints/openapi',
    defaultModel: 'gemini-2.0-flash',
    models: ['gemini-2.0-flash', 'gemini-2.5-pro'],
    auth: 'key',
    keyHint: '… (GCP OAuth / service key)',
    notes: 'Project + region specific; uses the OpenAI-compatible endpoint.',
  },
  {
    id: 'helicone',
    name: 'Helicone (LLM gateway)',
    group: 'cloud',
    adapter: 'openai',
    baseUrl: 'https://oai.helicone.ai/v1',
    defaultModel: 'openai/gpt-4o',
    models: ['openai/gpt-4o'],
    auth: 'key',
    keyHint: 'sk-helicone… (Helicone key)',
    notes: 'Observability gateway; forwards to OpenAI-compatible providers.',
  },
  {
    id: 'humain',
    name: 'HUMAIN',
    group: 'cloud',
    adapter: 'openai',
    baseUrl: 'https://api.humain.ai/v1',
    defaultModel: 'anthropic/claude-3-5-haiku',
    models: ['anthropic/claude-3-5-haiku'],
    auth: 'key',
    keyHint: '… (HUMAIN key)',
  },
  {
    id: 'bluelab',
    name: 'BlueLab (Metavata)',
    group: 'cloud',
    adapter: 'openai',
    baseUrl: 'https://api.bluelab.ai/v1',
    defaultModel: 'meta-llama/Llama-3.3-70B-Instruct',
    models: ['meta-llama/Llama-3.3-70B-Instruct'],
    auth: 'key',
    keyHint: '… (BlueLab key)',
  },
  {
    id: 'cerebras-2',
    name: 'Cerebras (Inference)',
    group: 'cloud',
    adapter: 'openai',
    baseUrl: 'https://api.cerebras.ai/v1',
    defaultModel: 'llama-3.3-70b',
    models: ['llama-3.3-70b'],
    auth: 'key',
    keyHint: '… (Cerebras key)',
  },
  {
    id: 'deepseek-v3',
    name: 'DeepSeek (Inference cache)',
    group: 'cloud',
    adapter: 'openai',
    baseUrl: 'https://api.deepseek.com/v1',
    defaultModel: 'deepseek-v3',
    models: ['deepseek-v3'],
    auth: 'key',
    keyHint: 'sk-… (DeepSeek key)',
  },
];

/* ------------------------------------------------------------------ *
 * Local — keyless or optional-key servers
 * ------------------------------------------------------------------ */

const local: ProviderCatalogEntry[] = [
  {
    id: 'ollama',
    name: 'Ollama',
    group: 'local',
    adapter: 'ollama',
    baseUrl: 'http://localhost:11434',
    defaultModel: 'qwen2.5',
    models: ['qwen2.5', 'llama3.2', 'qwen3', 'mistral'],
    auth: 'none',
    notes: 'Native Ollama /api/chat surface. No API key.',
  },
  {
    id: 'lmstudio',
    name: 'LM Studio',
    group: 'local',
    adapter: 'openai',
    baseUrl: 'http://localhost:1234/v1',
    defaultModel: 'local-model',
    models: ['local-model'],
    auth: 'optional',
    notes: 'Start the local server from LM Studio.',
  },
  {
    id: 'localai',
    name: 'LocalAI',
    group: 'local',
    adapter: 'openai',
    baseUrl: 'http://localhost:8080/v1',
    defaultModel: 'local-model',
    models: ['local-model'],
    auth: 'optional',
  },
  {
    id: 'vllm',
    name: 'vLLM',
    group: 'local',
    adapter: 'openai',
    baseUrl: 'http://localhost:8000/v1',
    defaultModel: 'local-model',
    models: ['local-model'],
    auth: 'optional',
  },
  {
    id: 'llamacpp',
    name: 'llama.cpp server',
    group: 'local',
    adapter: 'openai',
    baseUrl: 'http://localhost:8080/v1',
    defaultModel: 'local-model',
    models: ['local-model'],
    auth: 'optional',
    notes:
      'No API key. Start the server with `llama-server -m <model.gguf> -c <ctx>` and set the same value in the context window advanced option — the harness compacts inside the server\u2019s window, never past it.',
  },
  {
    id: 'koboldcpp',
    name: 'KoboldCpp',
    group: 'local',
    adapter: 'openai',
    baseUrl: 'http://localhost:5001/v1',
    defaultModel: 'local-model',
    models: ['local-model'],
    auth: 'optional',
  },
  {
    id: 'oobabooga',
    name: 'Text-Generation-WebUI (oobabooga)',
    group: 'local',
    adapter: 'openai',
    baseUrl: 'http://localhost:5000/v1',
    defaultModel: 'local-model',
    models: ['local-model'],
    auth: 'optional',
  },
  {
    id: 'jan',
    name: 'Jan',
    group: 'local',
    adapter: 'openai',
    baseUrl: 'http://localhost:1337/v1',
    defaultModel: 'local-model',
    models: ['local-model'],
    auth: 'optional',
  },
  {
    id: 'gpt4all',
    name: 'GPT4All',
    group: 'local',
    adapter: 'openai',
    baseUrl: 'http://localhost:4891/v1',
    defaultModel: 'local-model',
    models: ['local-model'],
    auth: 'optional',
  },
  {
    id: 'sglang',
    name: 'SGLang',
    group: 'local',
    adapter: 'openai',
    baseUrl: 'http://localhost:30000/v1',
    defaultModel: 'local-model',
    models: ['local-model'],
    auth: 'optional',
  },
  {
    id: 'anythingllm',
    name: 'AnythingLLM',
    group: 'local',
    adapter: 'openai',
    baseUrl: 'http://localhost:3001/v1',
    defaultModel: 'local-model',
    models: ['local-model'],
    auth: 'optional',
  },
  {
    id: 'tabbyapi',
    name: 'TabbyAPI (exui)',
    group: 'local',
    adapter: 'openai',
    baseUrl: 'http://localhost:5000/v1',
    defaultModel: 'local-model',
    models: ['local-model'],
    auth: 'optional',
  },
  {
    id: 'mlc',
    name: 'MLC LLM',
    group: 'local',
    adapter: 'openai',
    baseUrl: 'http://localhost:8080/v1',
    defaultModel: 'local-model',
    models: ['local-model'],
    auth: 'optional',
  },
  {
    id: 'openwebui',
    name: 'Open WebUI',
    group: 'local',
    adapter: 'openai',
    baseUrl: 'http://localhost:8080/v1',
    defaultModel: 'local-model',
    models: ['local-model'],
    auth: 'optional',
    notes: 'Proxies to a local backend; set the model to your backend model.',
  },
];

/* ------------------------------------------------------------------ *
 * Custom catch-all
 * ------------------------------------------------------------------ */

const custom: ProviderCatalogEntry[] = [
  {
    id: 'custom',
    name: 'Custom OpenAI-compatible endpoint',
    group: 'custom',
    adapter: 'openai',
    baseUrl: '',
    defaultModel: '',
    auth: 'optional',
    keyHint: '(leave empty for keyless, or paste a key)',
    notes: 'Any OpenAI-compatible /v1 endpoint (Azure OpenAI, AWS Bedrock via a proxy, corporate gateways). Enter the base URL and model yourself.',
  },
];

export const PROVIDER_CATALOG: ProviderCatalogEntry[] = [...cloud, ...local, ...custom];

const byId = new Map<string, ProviderCatalogEntry>(PROVIDER_CATALOG.map((p) => [p.id, p]));

/** Look up a catalog entry by id, or undefined when unknown. */
export function getProvider(id: string | undefined | null): ProviderCatalogEntry | undefined {
  if (!id) return undefined;
  return byId.get(id);
}

/** Provider entries grouped for the `<optgroup>` picker. */
export const PROVIDER_GROUPS: Array<{ group: ProviderCatalogEntry['group']; label: string; entries: ProviderCatalogEntry[] }> = [
  { group: 'cloud', label: 'Cloud', entries: cloud },
  { group: 'local', label: 'Local', entries: local },
  { group: 'custom', label: 'Custom', entries: custom },
];

export const LOCAL_PROVIDER_IDS = new Set(local.map((p) => p.id));
export const CUSTOM_PROVIDER_ID = 'custom';

/** True when a provider needs an API key (local keyless servers return false). */
export function requiresKey(entry: ProviderCatalogEntry | undefined): boolean {
  return entry ? entry.auth === 'key' : true;
}
