import { createHash, randomBytes, randomUUID } from 'node:crypto';
import { mkdir, readFile, rename, writeFile } from 'node:fs/promises';
import { join } from 'node:path';

/** Device tokens are stored SHA-256-hashed only — the plaintext lives
 *  exclusively on the phone (flutter_secure_storage). */
export function hashToken(token: string): string {
  return createHash('sha256').update(token, 'utf8').digest('hex');
}

export interface RemoteDevice {
  deviceId: string;
  name: string;
  tokenHash: string;
  createdAt: number;
  lastSeen: number;
}

export interface RemoteState {
  enabled: boolean;
  port: number;
  devices: RemoteDevice[];
}

export const DEFAULT_REMOTE_PORT = 8833;

const DEFAULT_STATE: RemoteState = { enabled: false, port: DEFAULT_REMOTE_PORT, devices: [] };

/**
 * Persistence for the remote bridge under userData/remote/:
 *
 *   state.json   { enabled, port, devices: [{deviceId, name, tokenHash,
 *                createdAt, lastSeen}] } — tokens are hashes only
 *   cert.pem     self-signed server certificate (generated by cert.ts)
 *   key.pem      its private key (mode 0600)
 *
 * Every write goes through tmp + rename so a crash can never leave a
 * half-written file (same discipline as SettingsStore/SessionStore).
 */
export class RemoteStore {
  private cache: RemoteState | null = null;

  constructor(private readonly dir: string) {}

  private stateFile(): string {
    return join(this.dir, 'state.json');
  }

  async get(): Promise<RemoteState> {
    if (this.cache) return this.cache;
    try {
      const raw = await readFile(this.stateFile(), 'utf8');
      const parsed = JSON.parse(raw) as Partial<RemoteState>;
      const devices = Array.isArray(parsed.devices)
        ? parsed.devices
            .filter((d): d is RemoteDevice => typeof d?.deviceId === 'string' && typeof d?.tokenHash === 'string')
            .map((d) => ({
              deviceId: d.deviceId,
              name: typeof d.name === 'string' ? d.name : 'Device',
              tokenHash: d.tokenHash,
              createdAt: typeof d.createdAt === 'number' ? d.createdAt : 0,
              lastSeen: typeof d.lastSeen === 'number' ? d.lastSeen : 0,
            }))
        : [];
      this.cache = {
        enabled: parsed.enabled === true,
        port: typeof parsed.port === 'number' && parsed.port > 0 && parsed.port < 65536 ? parsed.port : DEFAULT_REMOTE_PORT,
        devices,
      };
    } catch {
      this.cache = { ...DEFAULT_STATE };
    }
    return this.cache;
  }

  private async persist(state: RemoteState): Promise<void> {
    this.cache = state;
    await mkdir(this.dir, { recursive: true });
    const tmp = `${this.stateFile()}.tmp`;
    await writeFile(tmp, JSON.stringify(state, null, 2), 'utf8');
    await rename(tmp, this.stateFile());
  }

  async setEnabled(enabled: boolean): Promise<RemoteState> {
    const state = await this.get();
    const next = { ...state, enabled };
    await this.persist(next);
    return next;
  }

  async setPort(port: number): Promise<RemoteState> {
    const state = await this.get();
    const clamped = Number.isInteger(port) && port > 0 && port < 65536 ? port : DEFAULT_REMOTE_PORT;
    const next = { ...state, port: clamped };
    await this.persist(next);
    return next;
  }

  /** Registers a new device, returning its raw token (never persisted). */
  async addDevice(name: string): Promise<{ device: RemoteDevice; token: string }> {
    const state = await this.get();
    const token = randomBytes(32).toString('hex');
    const now = Date.now();
    const device: RemoteDevice = {
      deviceId: randomUUID(),
      name: name
        .trim()
        // eslint-disable-next-line no-control-regex
        .replace(/[\u0000-\u001f]/g, '')
        .slice(0, 64) || 'Device',
      tokenHash: hashToken(token),
      createdAt: now,
      lastSeen: now,
    };
    const devices = [...state.devices.filter((d) => d.deviceId !== device.deviceId), device];
    await this.persist({ ...state, devices });
    return { device, token };
  }

  async touchDevice(deviceId: string, at = Date.now()): Promise<void> {
    const state = await this.get();
    if (!state.devices.some((d) => d.deviceId === deviceId)) return;
    await this.persist({
      ...state,
      devices: state.devices.map((d) => (d.deviceId === deviceId ? { ...d, lastSeen: at } : d)),
    });
  }

  async revokeDevice(deviceId: string): Promise<boolean> {
    const state = await this.get();
    const devices = state.devices.filter((d) => d.deviceId !== deviceId);
    if (devices.length === state.devices.length) return false;
    await this.persist({ ...state, devices });
    return true;
  }
}
